"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestBaselineOfPharoFunctional,
	#superclass : #PackageManifest,
	#category : #'BaselineOfPharoFunctional-Manifest'
}

{ #category : #'code-critics' }
ManifestBaselineOfPharoFunctional class >> ruleUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#BaselineOfPharoFunctional)) #'2020-11-21T23:54:30.072513-05:00') )
]
