Extension { #name : #Bag }

{ #category : #'*CompileWithCompose' }
Bag >> eigthNamed: key [ 
	"Answer whether the set includes the key."

	^ self occurrencesOf: key
]

{ #category : #'*CompileWithCompose' }
Bag >> fifthNamed: key [ 
	"Answer whether the set includes the key."

	^ self occurrencesOf: key
]

{ #category : #'*CompileWithCompose' }
Bag >> firstNamed: key [ 
	"Answer whether the set includes the key."

	^ self occurrencesOf: key
]

{ #category : #'*CompileWithCompose' }
Bag >> fourthNamed: key [ 
	"Answer whether the set includes the key."

	^ self occurrencesOf: key
]

{ #category : #'*CompileWithCompose' }
Bag >> ninthNamed: key [ 
	"Answer whether the set includes the key."

	^ self occurrencesOf: key
]

{ #category : #'*CompileWithCompose' }
Bag >> secondNamed: key [ 
	"Answer whether the set includes the key."

	^ self occurrencesOf: key
]

{ #category : #'*CompileWithCompose' }
Bag >> seventhNamed: key [ 
	"Answer whether the set includes the key."

	^ self occurrencesOf: key
]

{ #category : #'*CompileWithCompose' }
Bag >> sixthNamed: key [ 
	"Answer whether the set includes the key."

	^ self occurrencesOf: key
]

{ #category : #'*CompileWithCompose' }
Bag >> thirdNamed: key [ 
	"Answer whether the set includes the key."

	^ self occurrencesOf: key
]
