Extension { #name : #Dictionary }

{ #category : #'*CompileWithCompose' }
Dictionary >> eighthNamed: key [ 
	"Answer the value associated with the key."

	^ self at: key
]

{ #category : #'*CompileWithCompose' }
Dictionary >> fifthNamed: key [ 
	"Answer the value associated with the key."

	^ self at: key
]

{ #category : #'*CompileWithCompose' }
Dictionary >> firstNamed: key [ 
	"Answer the value associated with the key."

	^ self at: key
]

{ #category : #'*CompileWithCompose' }
Dictionary >> fourthNamed: key [ 
	"Answer the value associated with the key."

	^ self at: key
]

{ #category : #'*CompileWithCompose' }
Dictionary >> ninthNamed: key [ 
	"Answer the value associated with the key."

	^ self at: key
]

{ #category : #'*CompileWithCompose' }
Dictionary >> secondNamed: key [ 
	"Answer the value associated with the key."

	^ self at: key
]

{ #category : #'*CompileWithCompose' }
Dictionary >> seventhNamed: key [ 
	"Answer the value associated with the key."

	^ self at: key
]

{ #category : #'*CompileWithCompose' }
Dictionary >> sixthNamed: key [ 
	"Answer the value associated with the key."

	^ self at: key
]

{ #category : #'*CompileWithCompose' }
Dictionary >> thirdNamed: key [ 
	"Answer the value associated with the key."

	^ self at: key
]
