Extension { #name : #SequenceableCollection }

{ #category : #'*CompileWithCompose' }
SequenceableCollection >> eighthNamed: unused [
	"Answer the first element of the receiver"
	"#(a b c d e f g h ) eighthNamed: #f >>> #a"

	^ self eighth
]

{ #category : #'*CompileWithCompose' }
SequenceableCollection >> fifthNamed: unused [
	"Answer the first element of the receiver"
	"#(a b c d e f g h ) fifthNamed: #f >>> #a"

	^ self fifth
]

{ #category : #'*CompileWithCompose' }
SequenceableCollection >> firstNamed: unused [
	"Answer the first element of the receiver"
	"#(a b c d e f g h ) firstNamed: #f >>> #a"

	^ self first
]

{ #category : #'*CompileWithCompose' }
SequenceableCollection >> fourthNamed: unused [
	"Answer the first element of the receiver"
	"#(a b c d e f g h ) fourthNamed: #f >>> #a"

	^ self fourth
]

{ #category : #'*CompileWithCompose' }
SequenceableCollection >> ninthNamed: unused [
	"Answer the first element of the receiver"
	"#(a b c d e f g h ) ninthNamed: #f >>> #a"

	^ self ninth
]

{ #category : #'*CompileWithCompose' }
SequenceableCollection >> secondNamed: unused [
	"Answer the first element of the receiver"
	"#(a b c d e f g h ) secondNamed: #f >>> #a"

	^ self second
]

{ #category : #'*CompileWithCompose' }
SequenceableCollection >> seventhNamed: unused [
	"Answer the first element of the receiver"
	"#(a b c d e f g h ) seventhNamed: #f >>> #a"

	^ self seventh
]

{ #category : #'*CompileWithCompose' }
SequenceableCollection >> sixthNamed: unused [
	"Answer the first element of the receiver"
	"#(a b c d e f g h ) sixthNamed: #f >>> #a"

	^ self sixth
]

{ #category : #'*CompileWithCompose' }
SequenceableCollection >> thirdNamed: unused [
	"Answer the first element of the receiver"
	"#(a b c d e f g h ) thirdNamed: #f >>> #a"

	^ self third
]
