Extension { #name : #Set }

{ #category : #'*CompileWithCompose' }
Set >> eighthNamed: key [ 
	"Answer whether the set includes the key."

	^ self includes: key
]

{ #category : #'*CompileWithCompose' }
Set >> fifthNamed: key [ 
	"Answer whether the set includes the key."

	^ self includes: key
]

{ #category : #'*CompileWithCompose' }
Set >> firstNamed: key [ 
	"Answer whether the set includes the key."

	^ self includes: key
]

{ #category : #'*CompileWithCompose' }
Set >> fourthNamed: key [ 
	"Answer whether the set includes the key."

	^ self includes: key
]

{ #category : #'*CompileWithCompose' }
Set >> ninthNamed: key [ 
	"Answer whether the set includes the key."

	^ self includes: key
]

{ #category : #'*CompileWithCompose' }
Set >> secondNamed: key [ 
	"Answer whether the set includes the key."

	^ self includes: key
]

{ #category : #'*CompileWithCompose' }
Set >> seventhNamed: key [ 
	"Answer whether the set includes the key."

	^ self includes: key
]

{ #category : #'*CompileWithCompose' }
Set >> sixthNamed: key [ 
	"Answer whether the set includes the key."

	^ self includes: key
]

{ #category : #'*CompileWithCompose' }
Set >> thirdNamed: key [ 
	"Answer whether the set includes the key."

	^ self includes: key
]
